### ISSUE TITLE
AndroidX build failure: cannot access SupportSQLiteDatabase

### ISSUE THREAD

**Issue by GrahamBorland** [requery/sqlite-android#89]
My project is using AndroidX.
```
android.enableJetifier=true
android.useAndroidX=true
```
All works fine with `io.requery:sqlite-android:3.23.1`.
It breaks with `3.26.0`.

```
e: /path/to/my/project/TrackingCursorFactory.java:9: error: cannot access SupportSQLiteDatabase
public final class TrackingCursorFactory implements io.requery.android.database.sqlite.SQLiteDatabase.CursorFactory {
             ^
  class file for androidx.sqlite.db.SupportSQLiteDatabase not found
```

**Comment by mikehardy** [comment]
Easy fix - you're missing a transitive dependency - https://github.com/ankidroid/Anki-Android/commit/addaac94667de9afbda5a34734314a5634acee6e is how I moved past requery 3.23.1 to 3.24 and you can look at the deps in the current master version of the same file for 3.26.0

I suppose this should be an extra line in the example gradle block in the README @npurushe

**Comment by GrahamBorland** [comment]
Thanks. It would be good to either add this requirement to the documentation, or just add the missing transitive dependency to this project.

**Comment by npurushe** [comment]
In the latest version of the library the Android X library dependencies are indicated as api dependencies (https://github.com/requery/sqlite-android/blob/master/sqlite-android/build.gradle#L47) so you shouldn't need to include them manually.

**Comment by mikehardy** [comment]
Yeah, I just removed that dependency from my project and my build still works - https://github.com/ankidroid/Anki-Android/pull/5239 (or, is working but it's 4 for 5 on emulator API levels in Travis and we're having some other flakiness issues...it'd be 0 for 5 if the dependency wasn't working)

**Comment by npurushe** [comment]
Should be resolved in the 3.27.1 version

**Comment by GrahamBorland** [comment]
Still a problem for me with 3.27.1 and 3.27.2.
It only works if I explicitly include the `androidx.sqlite` dependency in my own `build.gradle`.
```groovy
    api 'io.requery:sqlite-android:3.27.2'
    api 'androidx.sqlite:sqlite:2.0.1'
```

Running a dependencies report shows that `io.requery:sqlite-android` does not provide any transitive dependencies. The `androidx.sqlite` dependency is coming from my own `build.gradle`.

```
|    +--- io.requery:sqlite-android:3.27.2
|    +--- androidx.sqlite:sqlite:2.0.1
|    |    \--- androidx.annotation:annotation:1.0.2
```

**Comment by krunalpatel3** [comment]
thanks this thinks helped me.
